<?php
//НЕ РАБОЧИЙ ФАЙЛ - всё в Page
	$title = "Форма не работает";
	$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title) ?></h1>


<?php 

	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get("idpage"));
	echo $this->formRow($form->get("title")), "<br/>";
	echo $this->formRow($form->get("article")), "<br/>";
	echo $this->formRow($form->get("pub")), "<br/>";
	//echo $this->formSubmit($form->get("submit"));
	echo $this->form()->closeTag();
?>